-- TaskFlow schema for Cloudflare D1 (SQLite).
--
-- Differences from the Postgres/Supabase version, and why:
--   * UUID            -> TEXT. SQLite has no UUID type; ids are generated by the API.
--   * TEXT[] / JSONB  -> TEXT holding JSON. SQLite has no array or jsonb type.
--   * TIMESTAMPTZ     -> TEXT holding an ISO-8601 UTC string, which sorts correctly.
--   * BOOLEAN         -> INTEGER 0/1.
--   * DECIMAL         -> REAL.
--   * No Row Level Security. SQLite has none, so every authorization rule that
--     used to live in an RLS policy is enforced in the Pages Functions API
--     instead. Anything reaching this database is already considered authorized,
--     which is why the API must never expose a raw query path.
--
-- Apply locally:  npx wrangler d1 execute taskflow --local --file=./d1-schema.sql
-- Apply remotely: npx wrangler d1 execute taskflow --remote --file=./d1-schema.sql

PRAGMA foreign_keys = ON;

-- Identity comes from Cloudflare Access; email is the join key between the
-- Access JWT and this table. There are no passwords here by design.
CREATE TABLE IF NOT EXISTS users (
    uid            TEXT PRIMARY KEY,
    email          TEXT NOT NULL UNIQUE,
    display_name   TEXT NOT NULL,
    avatar         TEXT,
    role           TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('admin','manager','member','viewer')),
    department     TEXT,
    time_zone      TEXT,
    workload       INTEGER DEFAULT 40,
    is_active      INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    last_login     TEXT,
    created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    manager_id     TEXT REFERENCES users(uid),
    approval_limit REAL
);

CREATE TABLE IF NOT EXISTS projects (
    id            TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    description   TEXT DEFAULT '',
    owner_id      TEXT NOT NULL REFERENCES users(uid),
    members       TEXT NOT NULL DEFAULT '[]',   -- JSON array of user ids
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    color         TEXT DEFAULT 'bg-blue-500',
    is_template   INTEGER NOT NULL DEFAULT 0 CHECK (is_template IN (0,1)),
    template_id   TEXT,
    is_favorite   INTEGER NOT NULL DEFAULT 0 CHECK (is_favorite IN (0,1)),
    status        TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','on_hold','completed','archived')),
    health_status TEXT,
    sections      TEXT DEFAULT '[]',            -- JSON
    brief         TEXT,                         -- JSON
    start_date    TEXT,
    due_date      TEXT,
    visibility    TEXT NOT NULL DEFAULT 'team' CHECK (visibility IN ('public','private','team')),
    custom_fields TEXT DEFAULT '[]',            -- JSON
    tags          TEXT DEFAULT '[]',            -- JSON
    portfolio_id  TEXT
);

CREATE TABLE IF NOT EXISTS tasks (
    id              TEXT PRIMARY KEY,
    title           TEXT NOT NULL,
    description     TEXT DEFAULT '',
    status          TEXT NOT NULL DEFAULT 'To Do' CHECK (status IN ('To Do','In Progress','Done')),
    task_status     TEXT NOT NULL DEFAULT 'not_started'
                        CHECK (task_status IN ('not_started','in_progress','completed','on_hold','cancelled')),
    project_id      TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    section_id      TEXT,
    assignee_id     TEXT REFERENCES users(uid),
    created_by      TEXT NOT NULL REFERENCES users(uid),
    due_date        TEXT,
    due_time        TEXT,   -- 'HH:mm' local time-of-day; NULL means the deadline is date-only
    start_date      TEXT,
    completed_date  TEXT,
    scheduled_start TEXT,   -- planner time block
    scheduled_end   TEXT,
    priority        TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high','critical')),
    "order"         INTEGER NOT NULL DEFAULT 0,
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    dependencies    TEXT DEFAULT '[]',
    subtasks        TEXT DEFAULT '[]',
    parent_task_id  TEXT REFERENCES tasks(id),
    time_tracked    INTEGER NOT NULL DEFAULT 0,   -- minutes
    estimated_time  INTEGER,                      -- minutes
    custom_fields   TEXT DEFAULT '{}',
    tags            TEXT DEFAULT '[]',
    attachments     TEXT DEFAULT '[]',
    is_milestone    INTEGER NOT NULL DEFAULT 0 CHECK (is_milestone IN (0,1)),
    subtask_items   TEXT DEFAULT '[]',
    recurrence      TEXT
);

CREATE TABLE IF NOT EXISTS comments (
    id         TEXT PRIMARY KEY,
    text       TEXT NOT NULL,
    task_id    TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    user_id    TEXT NOT NULL REFERENCES users(uid),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT,
    is_edited  INTEGER NOT NULL DEFAULT 0 CHECK (is_edited IN (0,1))
);

CREATE TABLE IF NOT EXISTS time_entries (
    id          TEXT PRIMARY KEY,
    task_id     TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    user_id     TEXT NOT NULL REFERENCES users(uid),
    duration    INTEGER NOT NULL DEFAULT 0,   -- minutes
    description TEXT,
    start_time  TEXT NOT NULL,
    end_time    TEXT,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    is_running  INTEGER NOT NULL DEFAULT 0 CHECK (is_running IN (0,1)),
    category    TEXT,
    is_billable INTEGER NOT NULL DEFAULT 0 CHECK (is_billable IN (0,1))
);

CREATE TABLE IF NOT EXISTS calendar_events (
    id              TEXT PRIMARY KEY,
    title           TEXT NOT NULL,
    description     TEXT DEFAULT '',
    type            TEXT NOT NULL DEFAULT 'meeting'
                        CHECK (type IN ('meeting','focus','reminder','deadline','out_of_office','personal')),
    owner_id        TEXT NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
    start_time      TEXT NOT NULL,
    end_time        TEXT NOT NULL,
    is_all_day      INTEGER NOT NULL DEFAULT 0 CHECK (is_all_day IN (0,1)),
    location        TEXT,
    conference_link TEXT,
    attendees       TEXT NOT NULL DEFAULT '[]',  -- JSON: [{userId,email,name,response}]
    project_id      TEXT REFERENCES projects(id) ON DELETE SET NULL,
    task_ids        TEXT NOT NULL DEFAULT '[]',
    color           TEXT,
    reminders       TEXT NOT NULL DEFAULT '[]',  -- JSON: [{id,minutesBefore,channels}]
    recurrence      TEXT,                        -- JSON or NULL
    exceptions      TEXT NOT NULL DEFAULT '[]',  -- JSON: yyyy-mm-dd strings removed from the series
    status          TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed','tentative','cancelled')),
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    CHECK (end_time > start_time)
);

-- Attendee lookup: SQLite cannot index into JSON, so membership is kept in its
-- own table and written alongside calendar_events.attendees by the API.
CREATE TABLE IF NOT EXISTS calendar_event_attendees (
    event_id TEXT NOT NULL REFERENCES calendar_events(id) ON DELETE CASCADE,
    user_id  TEXT NOT NULL,
    PRIMARY KEY (event_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_tasks_project_id       ON tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee_id      ON tasks(assignee_id);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date         ON tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_status           ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_scheduled_start  ON tasks(scheduled_start);
CREATE INDEX IF NOT EXISTS idx_projects_owner_id      ON projects(owner_id);
CREATE INDEX IF NOT EXISTS idx_comments_task_id       ON comments(task_id);
CREATE INDEX IF NOT EXISTS idx_time_entries_task_id   ON time_entries(task_id);
CREATE INDEX IF NOT EXISTS idx_time_entries_user_id   ON time_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_events_owner_id        ON calendar_events(owner_id);
CREATE INDEX IF NOT EXISTS idx_events_start_time      ON calendar_events(start_time);
CREATE INDEX IF NOT EXISTS idx_event_attendees_user   ON calendar_event_attendees(user_id);

-- Keep updated_at honest without relying on every caller to set it.
CREATE TRIGGER IF NOT EXISTS projects_touch_updated_at
AFTER UPDATE ON projects FOR EACH ROW
BEGIN
    UPDATE projects SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS tasks_touch_updated_at
AFTER UPDATE ON tasks FOR EACH ROW
BEGIN
    UPDATE tasks SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
END;

CREATE TRIGGER IF NOT EXISTS calendar_events_touch_updated_at
AFTER UPDATE ON calendar_events FOR EACH ROW
BEGIN
    UPDATE calendar_events SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
END;
