CREATE TABLE IF NOT EXISTS users (
  uid            TEXT PRIMARY KEY,
  email          TEXT NOT NULL UNIQUE,
  display_name   TEXT NOT NULL,
  avatar         TEXT,
  role           TEXT NOT NULL DEFAULT 'member',
  department     TEXT,
  time_zone      TEXT,
  workload       INTEGER,
  is_active      INTEGER NOT NULL DEFAULT 1,
  last_login     TEXT,
  created_at     TEXT NOT NULL,
  manager_id     TEXT,
  approval_limit REAL
) STRICT;

CREATE TABLE IF NOT EXISTS projects (
  id             TEXT PRIMARY KEY,
  name           TEXT NOT NULL,
  description    TEXT,
  owner_id       TEXT NOT NULL REFERENCES users(uid),
  members        TEXT NOT NULL DEFAULT '[]',
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL,
  color          TEXT NOT NULL DEFAULT 'bg-slate-500',
  is_template    INTEGER NOT NULL DEFAULT 0,
  template_id    TEXT,
  is_favorite    INTEGER NOT NULL DEFAULT 0,
  status         TEXT NOT NULL DEFAULT 'active',
  health_status  TEXT,
  sections       TEXT NOT NULL DEFAULT '[]',
  brief          TEXT,
  status_updates TEXT NOT NULL DEFAULT '[]',
  start_date     TEXT,
  due_date       TEXT,
  visibility     TEXT NOT NULL DEFAULT 'team',
  custom_fields  TEXT NOT NULL DEFAULT '[]',
  tags           TEXT NOT NULL DEFAULT '[]',
  portfolio_id   TEXT
) STRICT;

CREATE TABLE IF NOT EXISTS tasks (
  id              TEXT PRIMARY KEY,
  title           TEXT NOT NULL,
  description     TEXT NOT NULL DEFAULT '',
  status          TEXT NOT NULL DEFAULT 'To Do',
  task_status     TEXT NOT NULL DEFAULT 'not_started',
  project_id      TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  project_ids     TEXT NOT NULL DEFAULT '[]',
  section_id      TEXT,
  assignee_id     TEXT,
  collaborator_ids TEXT NOT NULL DEFAULT '[]',
  created_by      TEXT,
  due_date        TEXT,
  due_time        TEXT,
  start_date      TEXT,
  completed_date  TEXT,
  scheduled_start TEXT,
  scheduled_end   TEXT,
  priority        TEXT NOT NULL DEFAULT 'medium',
  "order"         INTEGER NOT NULL DEFAULT 0,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL,
  dependencies    TEXT NOT NULL DEFAULT '[]',
  blocked_by      TEXT NOT NULL DEFAULT '[]',
  blocking        TEXT NOT NULL DEFAULT '[]',
  subtasks        TEXT NOT NULL DEFAULT '[]',
  parent_task_id  TEXT,
  time_tracked    INTEGER NOT NULL DEFAULT 0,
  estimated_time  INTEGER,
  custom_fields   TEXT NOT NULL DEFAULT '{}',
  tags            TEXT NOT NULL DEFAULT '[]',
  attachments     TEXT NOT NULL DEFAULT '[]',
  approval        TEXT,
  is_milestone    INTEGER NOT NULL DEFAULT 0,
  subtask_items   TEXT NOT NULL DEFAULT '[]',
  recurrence      TEXT,
  activities      TEXT NOT NULL DEFAULT '[]'
) STRICT;

CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks(assignee_id);
